### ISSUE TITLE
Assigning to the LAST array element throws compiler error N3058.

### ISSUE THREAD

**Issue by gitlarryf** [ghewgill/neon-lang#172] opened 2017-01-16 21:44 UTC
The following code results in a compiler error: N3058 "expression is not assignable".

     VAR arr: Array<String> := []
     arr[LAST] := "Test"

However, the following code works:

     VAR arr: Array<String> := []
     arr[LAST TO LAST] := ["Test"]

The code above also crashes the REPL.

**Comment by ghewgill** [comment] 2017-01-24 16:37
Duplicate of #163.

**Closed by ghewgill** 2017-01-24 16:37 UTC
Labels: bug
