### ISSUE TITLE
Bytecode constructor throws exception if provided data is not actually Neon Bytecode.

### ISSUE THREAD

**Issue by gitlarryf** [ghewgill/neon-lang#97] opened 2015-10-30 22:33 UTC
This happens most easily if a user attempts to use neonbind.exe and provides a .neon file, instead of a .neonx file, perhaps with the assumption that neonbind will compile the .neon file before building the executable.  To solve this problem, I recommend that neonx files contain "file magic" that identifies them as compiled neon binaries, while at the same time containing pointers that locate the file offsets for the String table, the Exception tables, etc., as well as the actual SOC, or Entry Point of the code.  This way, future versions of Neonx files can be modified, so long as there is some sort of metadata at the very top of the file to identify where things are in the file.  This can even be ASCII at the start of the file that contains JSON with metadata in it, allowing the programmers to perhaps insert their own metadata, like Version information, etc...  This prevents a major redesign of the Bytecode, and Bytecode class to alter the way it looks for the necessary pieces of a neonx in order to load it properly.

**Comment by ghewgill** [comment] 2015-10-31 01:13
Sure, this is a known issue. The issue is the bytecode loader currently does absolutely no validation of what it's actually loading. So, trying to load something that's not a correct bytecode file is likely to crash. Changing the bytecode file format won't fix this; what this needs is actual validation of bytecode data (no matter what the file format actually is).

**Closed** 2016-05-27 09:51 UTC
Labels: bug
