### ISSUE TITLE
Neon code that causes the compiler to crash

### ISSUE THREAD

**Issue by gitlarryf** [ghewgill/neon-lang#447] opened 2024-02-20 04:45 UTC
The following piece of code:
```
TYPE r IS RECORD
    a: Array<r>
END RECORD
print(r())
```
crashes the Neon compiler on Windows.

**Comment by ghewgill** [comment] 2024-02-21 07:56
Duplicate of #297

**Closed** 2024-02-26 17:35 UTC
